### ISSUE TITLE
Other Expermints

### ISSUE THREAD

**Issue by AmeenAli** [jsyoon0823/VIME#1]
Hi,
Thanks for sharing your awesome work!
I was searching for the other experiments done in the paper, and couldn't find any expect for the MNIST.
Where can I find the other experiments?
Thanks

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.
Unfortunately, most datasets that we used in this paper are private data.
Thus, I cannot share the code for those datasets.

So, I just publish the main codebase using public MNIST in this GitHub.
Also, we have no plan to extend this codebase to other datasets in the near future.

Thanks!
