### ISSUE TITLE
Expermints Results

### ISSUE THREAD

**Issue by AmeenAli** [jsyoon0823/VIME#2]
Hello,
I have tried to reproduce your results on MNIST dataset.
However I got the total performance of VIME = 92.44, in the paper was written 95%
I have used the default paper configs.
Thanks

**Comment by jsyoon0823** [comment]
Thanks for your comments.
You need to do some hyper-parameter tuning to get full 95%.
Current codebase is just easily and rapidly show the improvements from
supervised learning settings.
Thanks
