### ISSUE TITLE
reproducing results

### ISSUE THREAD

**Issue by ZhabizGIT** [jsyoon0823/VIME#4]
I am going to reproduce the results in your paper for the public tabular datasets(Blog and Income). Could you please let me know which value you picked for the hidden layer size of the encoder in self-supervised learning? It determines the dimension of latent representations.

Thanks,

**Comment by jsyoon0823** [comment]
Thank you for your interest in our paper.

We did some hyper-parameter tuning to decide the hidden layer size of the
encoder.
But we did not save the optimal hyper-parameters. Thus, we cannot provide
the exact values of the optimal hyper-parameters.

Thanks.
