### ISSUE TITLE
Encoding of categorical data

### ISSUE THREAD

**Issue by mortezamg63** [jsyoon0823/VIME#5]
Can you please let me know what kind of encoding you use on categorical data? 
Is it One-Hot encoding or label-encoding?
It seems to me you do not make difference among data in MNIST and categorical data. From the description in section 5.3 in the paper, it looks like that you use label encoding. is it right?

**Comment by jsyoon0823** [comment]
We use one-hot encoding for the categorical data as the input encoding for tabular data.
