### ISSUE TITLE
Hyperparameter space

### ISSUE THREAD

**Issue by davidfstein** [jsyoon0823/VIME#9]
I didn't see this mentioned in your manuscript, apologies if I missed it - could you give an estimate of a reasonable hyperparameter search space for tuning? I would like to tune VIME for my dataset, but I'm not sure what range of values is reasonable for the hyperparameters.

**Comment by jsyoon0823** [comment]
Thank you for your interests in our paper.

We described some hyper-parameter details in the supplementary materials
(see Section 5 in the supplementary materials in
https://proceedings.neurips.cc/paper/2020/hash/7d97667a3e056acab9aaf653807b4a03-Abstract.html
).

Thanks!
